name: getx_dev
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  dio: 5.4.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: 4.8.1
  json_serializable: ^6.7.1
  get: ^4.6.6
  get_it: ^7.6.7
  injectable: ^2.3.2
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:
  build_runner:
  freezed: ^2.4.7

flutter:
  uses-material-design: true
